class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'extract'
        self.TarMirrorCommand = 'tarmirror'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'copy'
        self.CountCommand = 'count'
        self.WatchCommand = 'ytdl'
        self.TarWatchCommand = 'playlist'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'

BotCommands = _BotCommands()
